members-only/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :users, only: [:index, :show] do 
    resources :posts, only: [:index]  # Nested route for user's posts
  end

  resources :posts # Standalone route for all posts

  get 'users_with_posts', to: 'users#display_users', as: 'users_with_posts'

  root "users#index"
end

members-only/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :body, presence: true
  validates :title, length: { in: 1..220 }
  validates :body, length: { in: 10..3000 }

  belongs_to :user
  has_rich_text :body
end

members-only/app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :username, :email, :password, presence: true
  validates :username, length: { minimum: 3 }
  validates :password, length: { in: 8..20 }
  validates :password, confirmation: true
  validates :email, format: { with: /\A[^@\s]+@[^@\s]+\.[^@\s]+\z/, message: "must be in the format 'string@string.string'" }
  validate :password_complexity

  has_many :posts, dependent: :destroy

  private

  def password_complexity
    if password.blank?
      errors.add(:password, "can't be blank")
    else
      unless password =~ /[!@#$%^&*]/
        errors.add(:password, "must include at least one symbol")
      end
  
      unless password =~ /[A-Z]/
        errors.add(:password, "must include at least one uppercase letter")
      end
  
      if password =~ /(\d)\1/
        errors.add(:password, "must not have consecutive identical digits")
      end
    end
  end
end

members-only/app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  helper Users::GreetingHelper
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end

end

members-only/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:user_id]  # Check if the request is for a specific user's posts
      @user = User.find(params[:user_id])
      @posts = @user.posts  # Fetch posts for that user
    else
      @posts = Post.all  # Fetch all posts if no user is specified
      respond_with(@posts)
    end
  end

  def show
    respond_with(@post)
  end

  def new
    @post = Post.new
    respond_with(@post)
  end

  def edit
    redirect_to posts_path, alert: "You can't edit this post, you didn't create it." unless @post.user == current_user
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.user == current_user
      @post.update(post_params)
      respond_with(@post)
    else
      redirect_to posts_path, alert: "You can't update this post, you didn't create it."
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy!
      respond_with(@post)
    else
      redirect_to posts_path, alert: "You can't delete this post, you didn't create it."
    end
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

members-only/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @posts = @user.posts
  end

  def display_users
    @users_with_posts = User.joins(:posts).distinct
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

members-only/app/helpers/users/greeting_helper.rb
module Users::GreetingHelper
  def time_based_greeting(user)
    time_of_day = Time.now.hour
    if time_of_day < 12
      "Good morning, #{user.username}!"
    elsif time_of_day < 18
      "Good afternoon, #{user.username}!"
    else
      "Good evening, #{user.username}!"
    end
  end
end

members-only/app/helpers/users/passwords_helper.rb
module Users::PasswordsHelper
end

members-only/app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

members-only/app/helpers/users/sessions_helper.rb
module Users::SessionsHelper
end

members-only/app/helpers/users_helper.rb
module UsersHelper
end

members-only/app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

members-only/app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

members-only/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <%= render "posts/shared/error_messages", resource: post %>

  <div class="form-floating mb-3">
    <%= form.text_field :title, class: "form-control", placeholder: "Leave a title of post here", id: "floatingInput" %>
    <%= form.label :title, "Title post here", for: "floatingInput" %>
    <% post.errors.full_messages_for(:title).each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>

  <div class="mb-3">
    <%= form.rich_text_area :body, class: "form-control", placeholder: "Leave a post here", id: "FormControlTextarea" %>
    <% post.errors.full_messages_for(:body).each do |message| %>
      <div class="alert alert-danger"><%= message %></div>
    <% end %>
  </div>

  <div class="mt-5">
    <%= form.submit "Create Post", class: "btn btn-primary btn-sm" %>
  </div>
<% end %>

members-only/app/views/posts/_post.html.erb
<div id="<%= dom_id post %>" class="card mb-3 post-card">
  <div class="card-body">
    <h5 class="card-title">
      <%= post.title %>
    </h5>

    <p class="card-text">
      <%= post.body %>
    </p>
  </div>
</div>

members-only/app/views/posts/edit.html.erb
<h1 class="mb-5">Editing post</h1>

<%= render "form", post: @post %>

<div>
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm mt-3" %>
</div>

members-only/app/views/posts/index.html.erb
<h1 class="mb-5">Posts</h1>

<% if @posts.any? %>
  <div id="posts" class="row">
    <% @posts.each do |post| %>
      <div class="col-md-4">
        <%= render post %>
        <p>
          <%= link_to "Show this post", post, class: "btn btn-primary btn-sm" %>
        </p>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="font-monospace mt-5 text-muted">This author hasn't written any posts yet.</p>
<% end %>


<div class="d-flex gap-2 mt-3">
  <%= link_to "New post", new_post_path, class: "btn btn-success btn-sm" %>
  <%= link_to "Back to users", params[:return_path] || users_path, class: "btn btn-secondary btn-sm" %>
</div>

members-only/app/views/posts/new.html.erb
<h1 class="mb-5">New post</h1>

<%= render "form", post: @post %>

<div class="mt-3">
  <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm" %>
</div>

members-only/app/views/posts/shared/_error_messages.html.erb
<% if @post.errors.any? %>
  <div class="my-3 text-danger font-monospace fs-6">
    <p><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</p>
  </div>
<% end %>

members-only/app/views/posts/show.html.erb
<div id="<%= dom_id @post %>">

  <div class="card mb-3 text-center pb-5">
    <div class="card-header px-0">
      <ul class="nav nav-tabs card-header-tabs px-5 mx-0 pt-4">
        <li class="nav-item">
          <%= link_to "Edit this post", edit_post_path(@post), class: "nav-link active", ariaCurrent: "true" %>
        </li>
        <li class="nav-item">
          <%= button_to "Destroy this post", @post, method: :delete, class: "nav-link text-danger" %>
        </li>
      </ul>
    </div>

    <div class="card-body px-5">
      <h3 class="card-title my-5">
        <%= @post.title %>
      </h3>
      <p class="card-text text-justify">
        <%= @post.body %>
      </p>
      <div class="d-flex flex-wrap justify-content-between align-items-center">
        <span class="text-start">
          <%= link_to "Back to posts", posts_path, class: "btn btn-secondary btn-sm" %>
        </span> 
        <% if user_signed_in? %>
          <figcaption class="font-monospace blockquote-footer m-0">
            written by <%= @post.user.username %>
          </figcaption>
        <% else %>
          <em class="text-primary">Please sign in to see the author of this post</em> 
        <% end %>
      </div>

    </div>
  </div>

</div>

members-only/app/views/users/_user.html.erb
<div id="<%= dom_id user %>" class="card mb-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Username:</strong>
      <%= user.username %>
    </p>

    <p class="card-text">
      <strong>Email:</strong>
      <%= user.email %>
    </p>
  </div>
</div>

members-only/app/views/users/display_users.html.erb
<!-- app/views/users/display_users.html.erb -->
<h1>Users with Posts</h1>

<div class="row">
  <% @users_with_posts.each do |user| %>
    <div class="col-md-4">
      <%= render user %>
      <div class="d-flex gap-2 mt-3">
        <p>
          <%= link_to "Show this user", user, class: "btn btn-primary btn-sm" %>
        </p>
        <p>
          <%= link_to "Look at #{user.username}'s posts", user_posts_path(user, return_path: request.path), class: "btn btn-secondary btn-sm" %>
        </p> 
      </div>      
    </div>
  <% end %>
</div>

<div class="d-flex gap-2 mt-3">
  <%= link_to "Back to users", users_path, class: "btn btn-secondary" %>
  <% if current_user %>
    <%= link_to "Look at my posts", user_posts_path(current_user), class: "btn btn-outline-info" %>
  <% end %>
</div>

members-only/app/views/users/index.html.erb
<h1 class="mb-5">Users</h1>

<div id="users" class="row">
  <% @users.each do |user| %>
    <div class="col-md-4">
      <%= render user %>
      <div class="d-flex gap-2 mt-3">
        <p>
          <%= link_to "Show this user", user, class: "btn btn-primary btn-sm" %>
        </p>
        <p>
          <%= link_to "Look at #{user.username}'s posts", user_posts_path(user), class: "btn btn-secondary btn-sm" %>
        </p> 
      </div>      
    </div>
  <% end %>
</div>

<% unless user_signed_in? %>
  <%= link_to "New user", new_user_registration_path, class: "btn btn-success mt-3" %>
<% end %>

<div class="d-flex gap-2 mt-3">
  <%= link_to "Look at posts", posts_path, class: "btn btn-outline-primary" %>
  <% if current_user %>
    <%= link_to "Look at my posts", user_posts_path(current_user), class: "btn btn-outline-info" %>
  <% end %>
  <%= link_to "Users who have posts", users_with_posts_path, class: "btn btn-outline-secondary"   %>
</div>

members-only/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div class="my-3 text-danger font-monospace fs-6">
    <p>
      <%= I18n.t(
        "errors.messages.not_saved", 
        count: resource.errors.count, 
        resource: resource.class.model_name.human.downcase
      ) %>
    </p>
  </div>
<% end %>

members-only/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-info btn-sm me-3" %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-warning btn-sm me-3" %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "font-monospace me-3" %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: "font-monospace me-3" %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: "font-monospace me-3" %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

members-only/app/views/users/show.html.erb
<%= render @user %>

<div class="d-flex gap-2 my-3">
  <%= link_to "Edit this user", edit_user_registration_path, class: "btn btn-warning btn-sm" %>
  <%= link_to "Back to users", users_path, class: "btn btn-secondary btn-sm" %>
  <%= button_to "Destroy this user", user_registration_path, method: :delete, class: "btn btn-danger btn-sm" %>
</div>

<% if @posts.any? %>
  <div><%= render 'layouts/accordion', posts: @posts %></div>
<% else %>
  <p class="font-monospace mt-5 text-muted">This author hasn't written any posts yet.</p>
<% end %>