private-events/config/routes.rb
Rails.application.routes.draw do
  resources :events
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    passwords: 'users/passwords'
  }

  resources :users, only: [:index, :show]
  resources :attendances, only: [:create, :destroy]

  get "home", to: "home#index"

  # Defines the root path route ("/")
  root "events#index"
end

private-events/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

private-events/app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :user_id, uniqueness: { scope: :event_id, message: "is already attending this event" }
end

private-events/app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', foreign_key: 'creator_id'
  has_many :attendances, dependent: :destroy
  has_many :attendees, through: :attendances, source: :user

  validates :title, presence: true, length: { minimum: 5, maximum: 100 } 
  validates :date, presence: true 
  validates :location, presence: true 
  validates :description, presence: true, length: { in: 10..3000 }

  scope :upcoming, -> { where("date >= ?", Time.zone.now).order(:date) }
  scope :past, -> { where("date < ?", Time.zone.now).order(:date) }
  
  
  def absent_location
    location.present? ? location : "Location didn't point"
  end
  
  private 
  
  def event_date_cannot_be_in_the_past 
    if date.present? && date < DateTime.now 
      errors.add(:date, "can't be in the past") 
    end 
  end
end

private-events/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, presence: true, length: { minimum: 3 }
  validate :password_complexity

  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :attendances, dependent: :destroy
  has_many :attended_events, through: :attendances, source: :event

  # Instance method to fetch upcoming attended events
  def upcoming_events
    attended_events.upcoming
  end

  # Instance method to fetch past attended events
  def past_events
    attended_events.past
  end

  private

  def password_complexity
    if password.present?
      unless password =~ /[!@#$%^&*]/
        errors.add :password, "must include at least one symbol"
      end

      unless password =~ /[A-Z]/
        errors.add :password, "must include at least one uppercase letter"
      end

      if password =~ /(\d)\1/
        errors.add :password, "must not have consecutive identical digits"
      end
    end
  end
end

private-events/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :email, :password, :password_confirmation, :current_password])
  end
end

private-events/app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    event = Event.find(params[:event_id])
    if current_user.attended_events.include?(event)
      redirect_to event, alert: 'You are already attending this event.'
    else
      current_user.attended_events << event
      redirect_to event, notice: 'Your ticket has been reserved!'
    end
  end

  def destroy
    attendance = current_user.attendances.find_by(event_id: params[:event_id])
    if attendance
      attendance.destroy
      redirect_to event_path(params[:event_id]), notice: 'You have successfully canceled your ticket.'
    else
      redirect_to event_path(params[:event_id]), alert: 'You are not attending this event.'
    end
  end
end

private-events/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_event, only: [:edit, :update, :destroy]
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by(id: params[:id])
      unless @event
        flash[:alert] = "Event not found."
        redirect_to events_path
      end
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :date, :location, :description)
    end

    def authorize_event
      unless @event&.creator == current_user
        flash[:alert] = "You are not authorized to perform this action."
        redirect_to events_path
      end
    end
    
end

private-events/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

private-events/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
end

private-events/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  respond_to :html, :turbo_stream
  
  protected

  def after_sign_up_path_for(resource)
    user_path(resource) # Redirect to the user's profile after signup
  end
  def after_update_path_for(resource)
    user_path(resource) # Redirect to the user's profile after updating
  end
  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path # Redirect to login page after logout
  end
end

private-events/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
end

private-events/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user.events
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
end

private-events/app/helpers/application_helper.rb
module ApplicationHelper
end

private-events/app/helpers/attendances_helper.rb
module AttendancesHelper
end

private-events/app/helpers/events_helper.rb
module EventsHelper
end

private-events/app/helpers/home_helper.rb
module HomeHelper
end

private-events/app/views/events/_event.html.erb
<% avatars = ["avatar/small/jenny.jpg", "avatar/small/christian.jpg", "avatar/small/stevie.jpg", "avatar/small/matt.jpg"] %>

<div id="<%= dom_id event %>">

  <div class="slideshow-container">
    <div class="slide fade">
      <%= image_tag 'avatar/large/wide_large.png', alt: 'Slide 1' %>
    </div>

    <div class="slide fade">
      <%= image_tag 'avatar/large/wide_blue_large.png', alt: 'Slide 2' %>
    </div>

    <!-- Navigation buttons -->
    <a class="prev" onclick="changeSlide(-1)"><%= content_tag :i, "", class: "chevron left icon ms-1" %></a>
    <a class="next" onclick="changeSlide(1)"><%= content_tag :i, "", class: "chevron right icon me-1" %></a>
  </div>

  <div class="ui grid">
    <div class="ten wide column">
      <h1 class="event-title">
        <%= event.title %>
      </h1>

      <div class="my-2">
        <h2>
          Date and time
        </h2>
        <p><%= content_tag :i, "", class: "calendar check outline icon me-1" %><%= event.date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y, %I:%M %p") %></p>
      </div>

      <div class="my-2">
        <h2>
        Location
        </h2>
          
        <p>   <!-- <i class="teal video icon"></i>   - it's usual icon in HTML doc -->
          <%= content_tag :i, "", class: "teal video icon" %>
          <%= event.location %>
        </p>
      </div>

      <div class="my-2">
        <h2>About this event</h2>
        <p>
          <%= event.description %>
        </p>
      </div>
      <div class="meta my-2">
        <i class="pencil alternate icon"></i>
        <span class="ui grey header space-mono-regular events-created">Events Created by <strong><%= event.creator[:username] %></strong></span>
      </div>
    </div>

    <div class="six wide column">

      <% if current_user == event.creator %>
        <h4 class="ui teal header my-5"><i class="calendar check outline icon"></i> You are the creator of this event!</h4>
      <% elsif current_user.attended_events.include?(@event) %>
        <h4 class="ui teal header my-5"><i class="calendar check outline icon"></i> You have already reserved a ticket for this event!</h4>
        <div class="ui cards">
          <div class="card pt-2">
            <div class="content">
              <%= button_to 'Cancel Ticket', attendance_path(event_id: @event.id), method: :delete, class: 'ui button fluid orange' %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="ui cards mt-5">
          <div class="card">
            <div class="content">
              <%= button_to 'Get Tickets', attendances_path(event_id: @event.id), method: :post, class: 'ui button primary fluid mt-5' %>
            </div>
          </div>
        </div>
      <% end %>

      <% if @event.attendees.any? %>
        <div class="mt-5">
          <h3>Attendees</h3>
            <dl>
              <% @event.attendees.each do |attendee| %>
                <div class="item mt-1">
                  <dt class="content">
                    <span class="header">
                      <%= image_tag cycle(*avatars), class: "ui avatar image" %>
                      <span class="space-mono-regular"> <%= attendee.username %> </span>
                    </span>
                  </dt>
                </div>
              <% end %>
            </dl>
        </div>
      <% elsif current_user != event.creator %>
        <h5 class="ui blue header my-5"><i class="calendar check outline icon"></i> Hurry up, you can become the first attendee</h5>
      <% end %>
    </div>
  </div>

</div>

private-events/app/views/events/_form.html.erb
<h2 class="ui header">Create Event</h2>

<%= form_with(model: event, html: { class: "ui form", "data-turbo" => "false" }) do |form| %>
  <% if event.errors.any? %>
    <div class="mb-3">
      <h5 class="ui red inverted header space-mono-regular"> <%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h5>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, placeholder: "Event Title", autofocus: true %>
    <% event.errors.full_messages_for(:title).each do |message| %>
      <h5 class="ui red inverted header space-mono-regular m-0">
        <small><%= message %></small>
      </h5>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_field :date, placeholder: "Event Date and Time" %>
    <% event.errors.full_messages_for(:date).each do |message| %>
      <h5 class="ui red inverted header space-mono-regular m-0">
        <small><%= message %></small>
      </h5>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location, placeholder: "Event Location" %>
    <% event.errors.full_messages_for(:location).each do |message| %>
      <h5 class="ui red inverted header space-mono-regular m-0">
        <small><%= message %></small>
      </h5>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, placeholder: "Event Description", rows: 4 %>
    <% event.errors.full_messages_for(:description).each do |message| %>
      <h5 class="ui red inverted header space-mono-regular m-0">
        <small><%= message %></small>
      </h5>
    <% end %>
  </div>

  <div class="field">
    <%= form.submit "Create Event", class: "ui primary button" %>
  </div>
<% end %>

private-events/app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render "form", event: @event %>

<br>

<div class="ui buttons">
  <%= link_to "Show this event", @event, class: "ui positive button" %> |
  <div class="or"></div>
  <%= link_to "Back to events", events_path, class: "ui button" %>
</div>

private-events/app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="ui centered header my-3">Events</h1>

<div class="ui two column grid">
  <div class="column">
    <div class="ui raised segment">
        <a class="ui teal ribbon label">Past</a>
        <% @events.past.each do |event| %>
          <h2>
            <%= event.title %>
          </h2>

          <p>
            <strong>Date:</strong>
            <%= event.date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y, %I:%M %p") %>
          </p>

          <p>
            <strong>Location:</strong>
          <!-- <i class="teal video icon"></i>   - it's usual icon in HTML doc -->
            <%= content_tag :i, "", class: "teal video icon ms-1" %>
            <%= event.location %>
          </p>

          <p>
            <strong>Description:</strong>
            <%= event.description %>
          </p>

          <p>
            <%= link_to "Show this event", event, class: "ui primary mini button" %>
          </p>
        <% end %>
    </div>
  </div>
  <div class="column">
    <div class="ui segment">
      <a class="ui orange right ribbon label">Upcoming</a>
      <% @events.upcoming.each do |event| %>
        <h2>
          <%= event.title %>
        </h2>

        <p>
          <strong>Date:</strong>
          <%= event.date.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y, %I:%M %p") %>
        </p>

        <p>
          <strong>Location:</strong>
        <!-- <i class="teal video icon"></i>   - it's usual icon in HTML doc -->
          <%= content_tag :i, "", class: "teal video icon ms-1" %>
          <%= event.location %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= event.description %>
        </p>

        <p>
          <%= link_to "Show this event", event, class: "ui primary mini button" %>
        </p>
      <% end %>
    </div>
  </div>
</div>

<%= link_to "New event", new_event_path, class: "ui green button mt-2" %>

private-events/app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Back to events", events_path %>
</div>

private-events/app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>


<div class="ui buttons">
  <%= link_to "Edit this event", edit_event_path(@event), class: "ui positive button" %> |
  <div class="or"></div>
  <%= link_to "Back to events", events_path, class: "ui button" %>
</div>
<%= button_to "Destroy this event", @event, method: :delete, class: "negative ui button my-1" %>

private-events/app/views/home/index.html.erb
<% avatars = ["avatar/small/jenny.jpg", "avatar/small/christian.jpg", "avatar/small/stevie.jpg", "avatar/small/matt.jpg"] %>

<h1 class="ui header">Home page</h1>
<div class="ui hidden section divider"></div>
<h2 class="ui header">Section One: Usernames</h2>


<div class="ui ordered horizontal list">
  <% @users.each do |user| %>
    <div class="item">
      <%= image_tag cycle(*avatars), class: "ui avatar image" %>
      <div class="content">
        <div class="header"><%= user.username %></div>
      </div>
    </div>
  <% end %>
</div>

<div class="ui section divider"></div>
<div class="ui hidden section divider"></div>

<h2 class="ui header">Section Two: User Details</h2>

<div class="ui ordered list">
  <% @users.each do |user| %>
    <div class="item">
      <div class="header"><%= user.email %></div>
      <div class="description">
        - <%= user.created_at.in_time_zone("Eastern Time (US & Canada)").strftime("%B %d, %Y, %I:%M %p") %>
      </div>
    </div>
  <% end %>
</div>